### ISSUE TITLE
fix using utf8 scripts.

### ISSUE THREAD

**Issue by AraHaan** [Myndale/KopiLua#2]
I got lua code that must be utf8 otherwise it breaks crap, some of it is in another language like korean for example, uses some other utf8 only characters etc.

So we need to have a fixed utf8 luac for c# like we have decompiler on.

**Comment by Myndale** [comment]
Hi AraHaan, thanks for your feedback. The primary design goal of KopiLua was to match the behaviour of the C code base as closely as possible. Multi-language support wasn't included in the official 5.1.4 release, and as such there are no plans to add it to KopiLua.

If KopiLua were to become more popular down the track then I would certainly consider upgrading it to match the most recent version of Lua, in which case it would inherit any changes that have been made since. In the mean time, I would recommend looking into 3rd-party libraries that allow unicode "strings" to be represented as byte arrays.
